
services:
  nestjs:
    image: nestjs
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '5001:3000' # expose-to-the-world : only-in-the-docker
    container_name: backend-app-tool-report
    networks:
      - server
networks:
  server: